stages:
    - test
    - deploy
    
test:
    image: python:3.8.8
    stage: test
    before_script:
    - apt -y update
    - pip install -r requirements.txt
   
    when: on_success
    script:
        - python manage.py migrate
        - python manage.py collectstatic --noinput
    only:
        - psmach
deploy:
    image: ruby:latest
    stage: deploy
    before_script:
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    environment:
        name: main
        url: $HEROKU_APP_HOST
    only:
        - psmach